### ISSUE TITLE
Clarify map-reduce vs MapReduce + mention manager-worker strategy (was: A few comments)

### ISSUE THREAD

**Issue by wrathematics** [HenrikBengtsson/article-bengtsson-future#7]
Did a quick scan of the paper and I think it's a great writeup. I just have a few comments.

* I would add a quick note deliberately distinguishing what you call map-reduce from the mapreduce algorithm of Dean and Ghemawat.
* I think it would be helpful to have a comment at the beginning on the kind of parallelism the paper describes. Specifically manager/worker as opposed to SPMD.

**Comment by HenrikBengtsson** [comment]
Hi Drew, thank you for this.  You're bringing up two important points.

> I would add a quick note deliberately distinguishing what you call map-reduce from the mapreduce algorithm of Dean and Ghemawat.

I've [updated](https://github.com/HenrikBengtsson/article-bengtsson-future/commit/60b0102a57a285d9c1ff5196a411fac23627c411) with a footnote:

> _We use the term ``map-reduce'' as it is used in functional programming. The \dfn{MapReduce} method by \citet{DeanGhemawat2004} was inspired by this term but they are not equivalent.._

I've actually been going back and forth on whether or not I should use "map-reduce" or "split-apply-combine" here - I went with the former for simplicity but still not certain.  Do you have any comments on which could be better/most informative here?  The "split" part is essential in parallel processing but it often doesn't mean the same as when we, for instance, use split-apply-combine for fitting models to subgroups of data.

> I think it would be helpful to have a comment at the beginning on the kind of parallelism the paper describes. Specifically manager/worker as opposed to SPMD.

I've [updated](https://github.com/HenrikBengtsson/article-bengtsson-future/commit/f7e6da464ce34f66038f714c8dbc61085617fa71) to now say:

> _... facilitate the most common types of parallel processing in R, especially the manager-worker strategy where an R process delegates tasks to other R processes._

**Comment by wrathematics** [comment]
I think the footnote clarifies things well. All of these terms have their own baggage and double meanings. Since you're likely submitting to an R journal (as opposed to a CS journal), I would avoid split-apply-combine, since as you point out, it has a particular meaning to the tidy people.

**Comment by HenrikBengtsson** [comment]
Thanks - I appreciate your insights.

I'm actually gonna re-open, to spare some else from make the same comments.   I've labeled it 'fixed'.  I'll close all 'fixed' when I've submitted v2 to arXiv.
