### ISSUE TITLE
Exception handling examples (minor suggestion)

### ISSUE THREAD

**Issue by zeehio** [HenrikBengtsson/article-bengtsson-future#8]
Thank you for the article. It was really nice to read.

I just have a very minor stylistic comment on the exception handling section. My primary language is not English and this may be a subjective issue, so free to close the issue if you prefer your current wording.

This structure seems less readable to me:

> For example, just like we get: 
(example 1)
 without futures, we get: 
(example 2)
 with futures. Standard mechanisms for...

than this alternative formulation:

> For example, just like without futures we get: 
(example 1)
with futures we get: 
(example 2)
Standard mechanisms for...

Because it introduces what the example is about ("without futures"/"with futures") before showing the actual example, so when I read the example I know exactly what to focus on.

Specifically I'm talking about these lines:

https://github.com/HenrikBengtsson/article-bengtsson-future/blob/6767bcb9577ed6776e3b1c4c66e81cc4da00595c/bengtsson-future.tex#L441-L455

Thanks again for your work and your time

**Comment by HenrikBengtsson** [comment]
Thank you, Sergio.  I agree that the flow is so-and-so in that passage. Others stumble upon it too.

I really struggled to rewrite it - I've probably tried 4-5 different alternatives until I surrendered and settled on (commit ae4ecfd):

https://github.com/HenrikBengtsson/article-bengtsson-future/blob/ae4ecfd56414821a22a81b3c6db0b0e3d370c1c6/bengtsson-future.tex#L446-L462

**Comment by zeehio** [comment]
Thank you!

**Comment by HenrikBengtsson** [comment]
As I said in another issue, I'm actually gonna re-open, to spare some else from repeating the same comments. I've labeled it 'fixed'. I'll close all 'fixed' when I've submitted v2 to arXiv.
